export const IMAGES = {
  awake: {
    background: "/awake/firstPage/background.webp",
    fireflies: "/awake/firstPage/fireflies.webp",
    art: "/awake/firstPage/art.webp",
    neonArt05: "/awake/firstPage/neonArt05.webp",
    neonArt01: "/awake/firstPage/neonArt01.webp",
    neonArt02: "/awake/firstPage/neonArt02.webp",
    neonArt03: "/awake/firstPage/neonArt03.webp",
    neonArt04: "/awake/firstPage/neonArt04.webp",
    track: "/awake/firstPage/track.webp",
    neon01: "/awake/firstPage/cityNeon01.webp",
    neon02: "/awake/firstPage/cityNeon02.webp",
    neon03: "/awake/firstPage/cityNeon03.webp",
    city: "/awake/firstPage/city.webp",
    girl: "/awake/firstPage/girl.webp",
    wheels: "/awake/firstPage/wheels.webp",
    droid: "/awake/firstPage/droid.webp",
    sphereInside: "/awake/sphere/sphereInside.webp",
    sphereOutside: "/awake/sphere/sphereOutside.webp",
    oko01: "/awake/sphere/oko01.webp",
    oko02: "/awake/sphere/oko02.webp",
    oko03: "/awake/sphere/oko03.webp",
    oko04: "/awake/sphere/oko04.webp",
    oko05: "/awake/sphere/oko05.webp",
    oko06: "/awake/sphere/oko06.webp",
    noise: "/awake/firstPage/noise.webp",
  },
  awake1: {
    fireflies: "/awake/secondPage/fireflies.png",
    frontNeon: "/awake/secondPage/frontNeon.png",
    frontRock: "/awake/secondPage/frontRock.png",
    neonArms: "/awake/secondPage/neonArms.png",
    neon: "/awake/secondPage/neon.png",
  },
  sleeping: {
    background: "/sleeping/firstPage/background.webp",
    fireflies: "/sleeping/firstPage/fireflies.webp",
    city: "/sleeping/firstPage/city.webp",
    art: "/sleeping/firstPage/art.webp",
    neon: "/sleeping/firstPage/neon.webp",
    mask02: "/sleeping/firstPage/mask02.webp",
    mask01: "/sleeping/firstPage/mask01.webp",
    fog02: "/sleeping/firstPage/fog02.webp",
    pillar: "/sleeping/firstPage/pillar.webp",
    fog01: "/sleeping/firstPage/fog01.webp",
    oko01: "/sleeping/sphere/oko01.webp",
    oko02: "/sleeping/sphere/oko02.webp",
    oko03: "/sleeping/sphere/oko03.webp",
    oko04: "/sleeping/sphere/oko04.webp",
    oko05: "/sleeping/sphere/oko05.webp",
    sphereInside: "/sleeping/sphere/sphereInside.webp",
    sphereOutside: "/sleeping/sphere/sphereOutside.webp",
    noise: "/sleeping/firstPage/noise.webp",
  },
  chose: {
    background: "/chose/background.png",
    sleep: "/chose/sleep.png",
    awake: "/chose/awake.png",
    light1: "/chose/light1.png",
    light2: "/chose/light2.png",
    light3: "/chose/light3.png",
    point: "/chose/point.svg",
    line: "/chose/line.svg",
    arrow: "/chose/arrow.svg",
    center: "/chose/center.svg",
  },
  sleeping1: {
    background: "/sleeping/secondPage/background1.webp",
    city: "/sleeping/secondPage/city2.webp",
    rock: "/sleeping/secondPage/rock3.webp",
    fog1: "/sleeping/secondPage/fog4.webp",
    fog2: "/sleeping/secondPage/fog5.webp",
    fog3: "/sleeping/secondPage/fog6.webp",
    stones1: "/sleeping/secondPage/stones7.webp",
    stone: "/sleeping/secondPage/stone.webp",
    stoneIllumination1: "/sleeping/secondPage/stoneIllumination8.webp",
    stones2: "/sleeping/secondPage/stones9.webp",
    stoneIllumination2: "/sleeping/secondPage/stoneIllumination10.webp",
    haze1: "/sleeping/secondPage/haze11.webp",
    rock2: "/sleeping/secondPage/rock2.webp",
    backlight: "/sleeping/secondPage/backlight13.webp",
    firelines: "/sleeping/secondPage/firelines14.webp",
    fog4: "/sleeping/secondPage/fog15.webp",
    fog5: "/sleeping/secondPage/fog16.webp",
  },
  ourTeam: {
    cinemarcle: "/ourTeam/cinemarcle.webp",
    lancheva: "/ourTeam/lancheva.webp",
    negleb: "/ourTeam/negleb.webp",
    pif: "/ourTeam/pif.webp",
    salamandra: "/ourTeam/salamandra.webp",
    sophie: "/ourTeam/sophie.webp",
    zlo: "/ourTeam/zlo.webp",
    kollab: "/ourTeam/kollab.webp",
  },
  arts: {
    firstSleeping: "/arts/firstSleeping.jpg",
    secondSleeping: "/arts/secondSleeping.jpg",
  },
  showdown: {
    art: "/showdown/art.jpg",
    gatherer: "/showdown/gatherer.jpg",
    rider: "/showdown/rider.jpg",
    third: "/showdown/third.png",
    stone: "/showdown/stone.png",
  },
  agreement: {
    art: "/agreement/art.png",
    first: "/agreement/first.png",
    fanatic: "/agreement/fanatic.png",
    screen: "/agreement/screen.png",
    logo: "/agreement/logo.png",
    cube: "/agreement/cube.png",
    opensea: "/agreement/opensea.svg",
  },
  modern: {
    bottom: "/modern/bottom.png",
    life: "/modern/life.png",
    people: "/modern/people.png",
    ayyon: "/modern/ayyon.png",
    logo: "/modern/logo.svg",
  },
  mint: {
    mintbg: "/mintbg.png",
    mintFinish: "/mintFinish.png",
    mintSecondLayer: "/mintSecondLayer.png",
    myth: "/myth.png",
  },
};

export const VIDEOS = {
  // terminalMP4: "/videos/terminal/TerminalEye2.mp4",
  // terminalWebm: "/videos/terminal/TerminalEye2.webm",
  sleepingSecondPageMP4: "/videos/sleeping/SleepingSecondPageVideo.mp4",
  sleepingSecondPageWebm: "/videos/sleeping/SleepingSecondPageVideo.webm",
  awakeSecondPageMP4: "/videos/awake/AwakeSecondPageVideo.mp4",
  awakeSecondPageWebm: "/videos/awake/AwakeSecondPageVideo.webm",

  // sleeping1: '/videos/sleepingPageVideo1.mp4',
};
